### ISSUE TITLE
使用CSS百分比padding来让固定比例的图片实现自适应

### ISSUE THREAD

**Issue by zhangxinmei** [zhangxinmei/summary#4]

**Comment by zhangxinmei** [comment]
# 背景
> 今天遇到一个背景图片自适应的问题，发现了一个padding的强大用法
> 发现可以用百分比padding来实现背景图片的自适应
# 实现原理
### padding百分比是相对于父元素宽度来计算的
首先要弄清楚一点：padding如果为百分比值，那么它是相对于父元素**宽度**来计算的

所以如果我们给盒子设置一个百分比上边距，让它能够撑出一块区域来，而这块区域就是我们希望图片所
占的区域，这时候再把盒子的高度设置为0，并且设置图片的background-size: cover，就可以轻松实现背景图片按百分比自适应了。那这个百分比是对少呢？百分比就是图片的宽高比。
```css
.mobile-banner{
        width: 100%;
        background:url(" ") center center no-repeat;
        background-size: cover;
        padding-top: width/height%;
        height: 0;
    }
```
参考：[张鑫旭：CSS百分比padding实现比例固定图片自适应布局](http://www.zhangxinxu.com/wordpress/2017/08/css-percent-padding-image-layout/)
