### ISSUE TITLE
CSS绝对定位absolute

### ISSUE THREAD

**Issue by zhangxinmei** [zhangxinmei/summary#8]

**Comment by zhangxinmei** [comment]
# 说明
> 昨天总结了一篇关于CSS实现水平垂直居中的问题，提到了使用绝对定位absolute来实现。但是今天早上看了张鑫旭大神关于absolute的几篇文章，发现absolute并没有想象中的单纯啊，如果没有正确使用，可能会带来很多麻烦。
#  absolute
首先我们来看一下对于[absolute](https://developer.mozilla.org/zh-CN/docs/Web/CSS/position)官方的解释：
不为元素预留空间，通过指定元素相对于最近的**非 static** 定位祖先元素的偏移，来确定元素位置。绝对定位的元素可以设置外边距（margins），且不会与其他边距合并。

所以我们也知道设置了position为absolute的元素会脱离文档流，把元素inline-block话，即元素的高度和宽度都会坍塌。
```html
   <div class="box">
        <img src="./p1.png" alt="">
    </div>
    <div class="box absolute">
        <img src="./p1.png" alt="">
    </div>
```
```css
    .box {
            padding: 20px;
            background: #888;
            margin-bottom: 10px;
        }

        .absolute {
            position: absolute;
        }
```
第一个没有加absolute的box按照正常的布局，宽度为100%，而第二个设置了absolute的box则变成自适应内部元素的宽度。
在此之前我只是理解到了这里，但是看了张鑫旭的[CSS 相对|绝对(relative/absolute)定位系列（一）](http://www.zhangxinxu.com/wordpress/2010/12/css-%E7%9B%B8%E5%AF%B9%E7%BB%9D%E5%AF%B9%E5%AE%9A%E4%BD%8D%E7%B3%BB%E5%88%97%EF%BC%88%E4%B8%80%EF%BC%89/)之后，我发现了absolute另一个惊人的秘密，就是如果设置了absolute元素，不仅会自身宽高坍塌，还会使其父元素高度坍塌，但是宽度不会坍塌。自己测试之后，真的是对absolute有了另一番看法，并不像之前想的那么简单，其破坏性跟float有的一拼啊，看来在以后再项目中不能随意乱用了。
```html
    <div class="box">
        <img src="./p1.png" alt="">
    </div>
```
```css
  .box {
            padding: 20px;
            background: #888;
            margin-bottom: 10px;
        }
        .box>img{
            position: absolute;
        }
```
